[build]
target = "i686-pc-windows-msvc"
rustflags = [
    "-C", "link-arg=/ENTRY:_shellcode",
    "-C", "link-arg=/MERGE:.edata=.rdata",
    "-C", "link-arg=/MERGE:.rustc=.data",
    "-C", "link-arg=/MERGE:.rdata=.text",
    "-C", "link-arg=/MERGE:.pdata=.text",
    "-C", "link-arg=/DEBUG:NONE",
    "-C", "link-arg=/EMITPOGOPHASEINFO",
    "-C", "link-arg=/SUBSYSTEM:WINDOWS",
    "-C", "target-feature=-mmx,-sse,+soft-float",
    "--emit", "asm",
]